import overnights from '@/assets/projects/overnights.webp';
import selii from '@/assets/projects/selii.png';
import faceself from '@/assets/projects/faceself.png';
import myPokedexUnir from '@/assets/projects/MyPokedexUnir.png';
import GuarapoSSR from '@/assets/projects/GuarapoSSR.png';
import unirFullstackTest from '@/assets/projects/UnirFullstackTest.png';

export const projectsConstants = {
  featuredProject: {
    title: 'Overnights',
    technologies: [
      'REACT',
      'SEQUELIZE',
      'MONGO',
      'VITE',
      'ZUSTAND',
      'CHARTJS',
      'AXIOS',
      'FRAMER',
      'LOTTIE',
      'MUI',
      'STYLED',
      'EXPRESS',
      'TYPESCRIPT',
      'MONGOOSE',
      'CLOUDINARY',
      'SENDGRID',
    ],
    github: undefined,
    image: overnights,
    deployment: 'https://www.overnights.com/',
    type: 'Freelance',
    role: 'Fullstack',
    description: 'Change Here!',
  },

  projects: [
    {
      title: 'My Pokedex UNIR',
      technologies: ['REACT', 'TYPESCRIPT', 'MUI', 'SASS', 'VITE', 'REDUX'],
      image: myPokedexUnir,
      github: 'https://github.com/JuankDawd/my-pokedex-unir',
      type: 'College Assignment',
      role: 'Frontend',
      deployment: 'https://my-pokedex-unir.netlify.app/',
    },
    {
      title: 'NextJs Portfolio with Framer and TailwindCss',
      technologies: ['NEXT', 'REACT', 'FRAMER', 'TAILWIND', 'TYPESCRIPT'],
      github:
        'https://github.com/JuankDawd/next.js-portfolio-with-framer-and-tailwindcss',
      image: overnights,
      type: 'Personal Development',
      role: 'Frontend',
      deployment:
        'https://next-js-portfolio-with-framer-and-tailwindcss.vercel.app/about',
    },
    {
      title: 'Guarapo-SSR',
      technologies: [
        'NEXT',
        'JEST',
        'TAILWIND',
        'TYPESCRIPT',
        'AXIOS',
        'PG',
        'PRISMA',
      ],
      github: 'https://github.com/JuankDawd/guarapo-ssr/tree/main',
      image: GuarapoSSR,
      type: 'Technical Review',
      role: 'Backend',
      deployment: 'https://guarapo-ssr.vercel.app/blocks/',
    },
    {
      title: 'UnirFullStackTest',
      technologies: [
        'JAVASCRIPT',
        'REACT',
        'ESLINT',
        'JEST',
        'SASS',
        'IONIC',
        'VITE',
      ],
      github: 'https://github.com/JuankDawd/UnirFullStackTest',
      image: unirFullstackTest,
      type: 'Fullstack',
      role: 'Frontend',
      deployment: '',
    },
    {
      title: 'Selii Ecommerce',
      technologies: [
        'JAVASCRIPT',
        'REACT',
        'MUI',
        'CSS',
        'STORYBOOKS',
        'IONIC',
        'VITE',
      ],
      github: undefined,
      image: selii,
      type: 'Freelance',
      role: 'Frontend',
      deployment: '',
    },
    {
      title: 'Faceself',
      technologies: [
        'IONIC',
        'REACT',
        'REDUX',
        'SASS',
        'AXIOS',
        'CAPACITOR',
        'CHARTJS',
        'TYPESCRIPT',
      ],
      github: undefined,
      image: faceself,
      type: 'Freelance Job',
      role: 'Mobile',
      deployment: '',
    },
    {
      title: 'Cheeseokay',
      technologies: [
        'ANGULAR',
        'CAPACITOR',
        'AUTH0',
        'SWIPER',
        'NGX-DATATABLE',
        'ESLINT',
        'EXPRESS',
        'EPAYCO',
        'CLOUDINARY',
        'FIREBASE',
        'MYSQL',
        'SIIGO',
        'PG',
        'SEQUELIZE',
        'TYPESCRIPT',
        'NODEMAILER',
      ],
      github: undefined,
      image: overnights,
      type: 'Freelance Job',
      role: 'Fullstack',
      deployment: '',
    },
    {
      title: 'Kommit',
      technologies: [
        'RAILS',
        'SQLITE3',
        'SHOULDA-MATCHERS',
        'RSPEC-RAILS',
        'FAKER',
        'FACTORY-BOT-RAILS',
        'BYE-BUG',
        'PG',
        'SASS',
        'TAILWIND',
      ],
      github: undefined,
      image: overnights,
      type: 'Freelance Job',
      role: 'Frontend',
      deployment: '',
    },
    {
      title: 'Doc.tors',
      technologies: [
        'FLUTTER',
        'RXDART',
        'HTTP',
        'FILE-PICKER',
        'PROGRESS-DIALOG',
        'AWESOME-DIALOG',
        'SOCKET-IO',
        'AGORA-RTC',
        'PERMISSION-HANDLER',
        'JWT',
        'ONE-SIGNAL',
      ],
      github: undefined,
      image: overnights,
      type: 'Freelance Job',
      role: 'Fullstack',
      deployment: '',
    },
  ],
};
