import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'

import { Navbar } from '@/components/Navbar'
import Head from './Head'

import './globals.css'
import Footer from '@/components/UI/Footer'

const roboto = Roboto_Mono({ subsets: ['latin'], variable: '--font-rob' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <Head />
      <body className={`w-full bg-background ${roboto.className} font-rob`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
