const skill = (name: string) => `/2025/Skills/${name}.svg`
const project = (name: string, ext = 'png') => `/2025/projects/${name}.${ext}`

export const projectsConstants = {
	featuredProject: {
		title: 'Overnights',
		technologies: [
			{ icon: skill('React'), name: 'React' },
			{ icon: skill('Sequelize'), name: 'Sequelize' },
			{ icon: skill('Mongo'), name: 'Mongo' },
			{ icon: skill('Vite'), name: 'Vite' },
			{ icon: skill('Zustand'), name: 'Zustand' },
			{ icon: skill('Chart.js'), name: 'Chartjs' },
			{ icon: skill('Axios'), name: 'Axios' },
			{ icon: skill('Framer'), name: 'Framer' },
			{ icon: skill('Lottie'), name: 'Lottie' },
			{ icon: skill('MUI'), name: 'MUI' },
			{ icon: skill('StyledComponents'), name: 'Styled Components' },
			{ icon: skill('Express'), name: 'Express' },
			{ icon: skill('TypeScript'), name: 'TypeScript' },
			{ icon: skill('mongoose'), name: 'Mongoose' },
			{ icon: skill('Cloudinary'), name: 'Cloudinary' },
			{ icon: skill('TwilioSendgrid'), name: 'Sendgrid' },
		],
		github: undefined,
		image: project('overnights', 'webp'),
		deployment: 'https://www.overnights.com/',
		type: 'Freelance',
		role: 'Fullstack',
		description:
			"Discover stress-free travel with Overnights—an intuitive app that simplifies your accommodation search. Easily find the perfect place for your stay with just a few taps, tailored to your preferences. For Jewish travelers, Overnights goes the extra mile by allowing you to locate kosher-friendly establishments and refine your search based on specific kosher standards. Whether you're a business traveler or a family on vacation, experience worry-free journeys with Overnights—your ultimate travel companion.",
	},

	projects: [
		{
			title: 'My Pokedex UNIR',
			technologies: [
				{ icon: skill('React'), name: 'React' },
				{ icon: skill('TypeScript'), name: 'TypeScript' },
				{ icon: skill('MUI'), name: 'MUI' },
				{ icon: skill('Sass'), name: 'Sass' },
				{ icon: skill('Vite'), name: 'Vite' },
				{ icon: skill('ReduxToolkit'), name: 'ReduxToolkit' },
			],
			image: project('MyPokedexUnir'),
			github: 'https://github.com/Juandawd/my-pokedex-unir',
			type: 'College Assignment',
			role: 'Frontend',
			deployment: 'https://my-pokedex-unir.netlify.app/',
		},
		{
			title: 'Modern Portfolio',
			technologies: [
				{ icon: skill('Nextjs'), name: 'NextJs' },
				{ icon: skill('React'), name: 'React' },
				{ icon: skill('Framer'), name: 'Framer' },
				{ icon: skill('Tailwind'), name: 'Tailwind' },
				{ icon: skill('TypeScript'), name: 'TypeScript' },
			],
			github:
				'https://github.com/Juandawd/next.js-portfolio-with-framer-and-tailwindcss',
			image: project('overnights', 'webp'),
			type: 'Personal Development',
			role: 'Frontend',
			deployment:
				'https://next-js-portfolio-with-framer-and-tailwindcss.vercel.app/',
		},
		{
			title: 'Guarapo-SSR',
			technologies: [
				{ icon: skill('Nextjs'), name: 'NextJs' },
				{ icon: skill('Jest'), name: 'Jest' },
				{ icon: skill('Tailwind'), name: 'Tailwind' },
				{ icon: skill('TypeScript'), name: 'TypeScript' },
				{ icon: skill('Axios'), name: 'Axios' },
				{ icon: skill('Postgres'), name: 'Postgres' },
				{ icon: skill('Prisma'), name: 'Prisma' },
			],
			github: 'https://github.com/Juandawd/guarapo-ssr/tree/main',
			image: project('GuarapoSSR'),
			type: 'Technical Review',
			role: 'Backend',
			deployment: 'https://guarapo-ssr.vercel.app/blocks/',
		},
		{
			title: 'UnirFullStackTest',
			technologies: [
				{ icon: skill('JavaScript'), name: 'JavaScript' },
				{ icon: skill('React'), name: 'React' },
				{ icon: skill('ESLint'), name: 'ESLint' },
				{ icon: skill('Jest'), name: 'Jest' },
				{ icon: skill('Sass'), name: 'Sass' },
				{ icon: skill('Ionic'), name: 'Ionic' },
				{ icon: skill('Vite'), name: 'Vite' },
			],
			github: 'https://github.com/Juandawd/UnirFullStackTest',
			image: project('UnirFullstackTest'),
			type: 'Fullstack',
			role: 'Frontend',
			deployment: '',
		},
		{
			title: 'Selii Ecommerce',
			technologies: [
				{ icon: skill('JavaScript'), name: 'JavaScript' },
				{ icon: skill('React'), name: 'React' },
				{ icon: skill('MUI'), name: 'MUI' },
				{ icon: skill('CSS3'), name: 'CSS3' },
				{ icon: skill('Storybook'), name: 'Storybooks' },
				{ icon: skill('Ionic'), name: 'Ionic' },
				{ icon: skill('Vite'), name: 'Vite' },
			],
			github: undefined,
			image: project('selii'),
			type: 'Freelance',
			role: 'Frontend',
			deployment: '',
		},
		{
			title: 'Faceself',
			technologies: [
				{ icon: skill('Ionic'), name: 'Ionic' },
				{ icon: skill('React'), name: 'React' },
				{ icon: skill('ReduxToolkit'), name: 'Redux Toolkit' },
				{ icon: skill('Sass'), name: 'Sass' },
				{ icon: skill('Axios'), name: 'Axios' },
				{ icon: skill('Capacitor'), name: 'Capacitor' },
				{ icon: skill('Chart.js'), name: 'Chartjs' },
				{ icon: skill('TypeScript'), name: 'TypeScript' },
			],
			github: undefined,
			image: project('faceself'),
			type: 'Freelance Job',
			role: 'Mobile',
			deployment: '',
		},
	],
}
